#ifndef __EMB_SERIAL_DEFS_H__
#define __EMB_SERIAL_DEFS_H__
#include "config.h"

#define MYNULL  NULL
//Error Codes
#define BASE_SERIAL_STATUS_CODE 0x1000

#define SERIAL_STATUS_ERROR (BASE_SERIAL_STATUS_CODE | 0x0001)
#define SERIAL_STATUS_OK    (BASE_SERIAL_STATUS_CODE)

#define SERIAL_STATUS_ARG_IS_NULL      (SERIAL_STATUS_ERROR + 1)
#define SERIAL_STATUS_ARG_IS_INVALID   (SERIAL_STATUS_ARG_IS_NULL + 1)
#define SERIAL_STATUS_NOT_IMPLEMENTED  (SERIAL_STATUS_ARG_IS_INVALID + 1)
#define SERIAL_STATUS_NOT_SUPPORTED    (SERIAL_STATUS_NOT_IMPLEMENTED + 1)


#endif //__EMB_SERIAL_DEFS_H__